### ISSUE TITLE
Problème de duplicité d'id de commentaire

### ISSUE THREAD

**Issue by NicolasMouret** [ArnaudPithon/ogalerie-back#6]
Je penses que les issues te manque alors voilà ! 
J'a voulu tester le back en local avec le seeding à jour, et je tombe parfois sur une erreur en voulant poster un commentaire : 

`Error: la valeur d'une clé dupliquée rompt la contrainte unique « art_comment_pkey »`

Il semblerait que parfois à la création d'un commentaire la bdd tente de générer un id déjà existant.
J'ai pas vu de contexte particulier où ça arrive, ça me parait aléatoire en testant plusieurs cas (sa propre oeuvre en tant qu'artiste ou l'oeuvre d'un autre artiste, des commentaires déjà présent ou pas sur l'oeuvre etc...)

Si jamais tu as l'occasion d'y jeter un oeil ;)

**Comment by ArnaudPithon** [comment]
Je pense savoir quel est le problème. Je regarde ça demain soir.

**Comment by ArnaudPithon** [comment]
Le bug devrait être corrigé.

**Comment by ArnaudPithon** [comment]
Pour ne pas avoir à reconstruire toute la base et perdre les nouvelles entrées que tu as pu faire :
```
# Dans le terminal
psql -d ogalerie -U ogalerie_api

-- Dans la console postgres
set role ogalerie_admin ;
\i src/data/update/patch-04.pgsql
```

**Comment by NicolasMouret** [comment]
Parfait ça a l'air d'être ok
